[package]
name = "whim-zed"
description = "Whim language support for Zed."
version = "0.2.0"
edition = "2024"
authors = ["Seifeddine Gmati <azjezz@carthage.software>"]
license = "MIT"
rust-version = "1.90"
repository = "https://github.com/carthage-software/whim-zed"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
zed_extension_api = "0.7.0"

[lints.rust]
unsafe_code = "forbid"
unused_imports = "deny"
unused_qualifications = "deny"

[lints.clippy]
all = { level = "deny", priority = -1 }
nursery = { level = "deny", priority = -1 }
pedantic = { level = "deny", priority = -1 }
