id = "whim-lang"
name = "Whim Language Support"
description = "Language support for Whim."
version = "0.15.0"
schema_version = 1
authors = ["Seifeddine Gmati <azjezz@carthage.software>"]
repository = "https://github.com/carthage-software/whim-zed"

[grammars.whim]
repository = "https://github.com/carthage-software/tree-sitter-whim"
commit = "6715b6934fba82a2d5b77cd50874a4de79c8c7ab"

[language_servers.whim]
name = "Whim"
languages = ["Whim"]
